# Generated by Django 4.1.3 on 2022-11-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birth_date'),
        ('workspaces', '0005_board_created_at_board_updated_at_file_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='boards', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='workspaces.label'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='workspaces', to='accounts.profile'),
        ),
    ]
