# Generated by Django 4.1.3 on 2022-11-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_workspace_owner'),
        ('workspaces', '0007_alter_board_admins'),
        ('workspaces', '0008_alter_board_members_alter_task_labels_and_more'),
    ]

    operations = [
    ]
