# Generated by Django 4.1.3 on 2022-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_starred_boards'),
        ('workspaces', '0011_rename_workers_task_doers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='doers',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
