# Generated by Django 4.1.3 on 2022-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_alter_task_doers_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='spend',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
