# Generated by Django 4.1.3 on 2022-12-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_rename_file_url_attachment_file'),
        ('workspaces', '0015_merge_20221206_2042'),
        ('workspaces', '0015_merge_20221207_1643'),
    ]

    operations = [
    ]
