# Generated by Django 4.1.3 on 2022-12-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_merge_20221207_1743'),
        ('workspaces', '0016_merge_20221208_0014'),
    ]

    operations = [
    ]
