# Generated by Django 4.1.3 on 2022-12-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_alter_boardtemplate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='board_template',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='board_template',
        ),
        migrations.AddField(
            model_name='board',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='workspaces.workspace'),
        ),
        migrations.DeleteModel(
            name='BoardTemplate',
        ),
    ]
