# Generated by Django 4.1.3 on 2022-12-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0024_remove_label_board_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='workspaces.workspace'),
        ),
    ]
