# Generated by Django 4.1.3 on 2022-12-22 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_starred_boards'),
        ('workspaces', '0028_merge_0024_task_order_0027_alter_board_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUserRecentBoards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastseen', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'board')},
            },
        ),
    ]
