# Generated by Django 4.1.3 on 2023-03-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_starred_boards'),
        ('workspaces', '0031_alter_board_background_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.RemoveField(
            model_name='board',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='task',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='label',
            name='board',
        ),
        migrations.AlterUniqueTogether(
            name='loguserrecentboards',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='loguserrecentboards',
            name='board',
        ),
        migrations.RemoveField(
            model_name='loguserrecentboards',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='task',
            name='doers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tasklist',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='board',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='CheckList',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='LogUserRecentBoards',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
