# Generated by Django 4.1.3 on 2022-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birth_date'),
        ('workspaces', '0002_alter_board_workspace'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='membership',
            name='board',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='tasklabel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tasklabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='tasklabel',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='workson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workson',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='workson',
            name='task',
        ),
        migrations.AddField(
            model_name='board',
            name='admins',
            field=models.ManyToManyField(related_name='administrating_boards', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='tasks', to='workspaces.label'),
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(related_name='tasks', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='BoardAdmin',
        ),
        migrations.DeleteModel(
            name='MemberShip',
        ),
        migrations.DeleteModel(
            name='TaskLabel',
        ),
        migrations.DeleteModel(
            name='WorksOn',
        ),
    ]
