# Generated by Django 4.1.3 on 2022-11-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birth_date'),
        ('workspaces', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', to='accounts.profile'),
        ),
    ]
