# Generated by Django 4.1.3 on 2022-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_birth_date'),
        ('workspaces', '0006_alter_board_members_alter_task_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administrating_boards', to='accounts.profile'),
        ),
    ]
