# Generated by Django 4.1.3 on 2022-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_board_members_alter_task_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
