# Generated by Django 4.1.3 on 2022-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_merge_20221123_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
