# Generated by Django 4.1.3 on 2022-12-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_tasklist_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='workers',
            new_name='doers',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_list',
            new_name='tasklist',
        ),
    ]
