# Generated by Django 4.1.3 on 2022-12-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_alter_task_estimate_alter_task_spend'),
        ('workspaces', '0014_alter_comment_reply_to'),
    ]

    operations = [
    ]
