# Generated by Django 4.1.3 on 2022-12-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_merge_20221206_2107'),
        ('workspaces', '0018_alter_attachment_created_at'),
    ]

    operations = [
    ]
