# Generated by Django 4.1.3 on 2022-12-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_boardtemplate_tasklist_board_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='board_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='workspaces.boardtemplate'),
        ),
    ]
