# Generated by Django 4.1.3 on 2022-12-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_merge_20221208_1748'),
        ('workspaces', '0024_task_order'),
    ]

    operations = [
    ]
