# Generated by Django 4.1.3 on 2022-12-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0024_task_order'),
        ('workspaces', '0027_alter_board_workspace'),
    ]

    operations = [
    ]
