# Generated by Django 4.1.3 on 2022-12-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_merge_0019_merge_20221208_1748_0024_task_order'),
        ('workspaces', '0028_merge_0024_task_order_0027_alter_board_workspace'),
    ]

    operations = [
    ]
