# Generated by Django 4.1.3 on 2022-12-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0029_merge_20221222_2002'),
        ('workspaces', '0030_rename_user_loguserrecentboards_profile_and_more'),
    ]

    operations = [
    ]
