# Generated by Django 4.1.3 on 2023-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0030_rename_user_loguserrecentboards_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='background_pics/'),
        ),
    ]
