# Generated by Django 4.1.3 on 2022-11-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_merge_20221123_1601'),
        ('accounts', '0006_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starred_boards',
            field=models.ManyToManyField(blank=True, related_name='starred_for', to='workspaces.board'),
        ),
    ]
