# Generated by Django 4.1.3 on 2023-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('accounts', '0007_profile_starred_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='starred_boards',
            field=models.ManyToManyField(blank=True, related_name='starred_for', to='board.board'),
        ),
    ]
