# Generated by Django 4.1.3 on 2023-04-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_starred_boards'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_multianswer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='board.poll')),
                ('voter', models.ManyToManyField(related_name='votes', to='accounts.profile')),
            ],
        ),
    ]
