# Generated by Django 4.1.3 on 2023-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_poll_pollanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollanswer',
            old_name='voter',
            new_name='voters',
        ),
        migrations.AddField(
            model_name='poll',
            name='is_known',
            field=models.BooleanField(default=True),
        ),
    ]
