# Generated by Django 4.1.3 on 2023-04-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_poll_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanswer',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
