# Generated by Django 4.1.3 on 2023-04-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_starred_boards'),
        ('board', '0005_pollanswer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
