# Generated by Django 4.1.3 on 2022-11-13 20:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "09123456789". Up to 15 digits allowed.', regex='^09\\d{9}$')])),
                ('profile_pic', models.CharField(blank=True, max_length=1000, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
