# Generated by Django 4.1.3 on 2023-05-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_starred_boards'),
        ('board', '0006_poll_creator'),
        ('retro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrosession',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrating_retro_sessions', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='retrosession',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retro_sessions', to='board.board'),
        ),
    ]
