# Generated by Django 4.1.3 on 2023-05-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0002_alter_retrosession_admin_alter_retrosession_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrocard',
            name='card_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retro_cards', to='retro.cardgroup'),
        ),
    ]
