# Generated by Django 4.1.3 on 2023-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_cardgroup_is_discussed_retrocard_is_positive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrosession',
            name='retro_step',
            field=models.SmallIntegerField(default=0),
        ),
    ]
