# Generated by Django 4.1.3 on 2023-05-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0008_retroreaction_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retroreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='retrosession',
            name='group_votes',
            field=models.IntegerField(default=-1, help_text='the default is -1 which means no limitation'),
        ),
    ]
