# Generated by Django 4.1.3 on 2023-05-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0009_alter_retroreaction_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrosession',
            name='group_votes',
        ),
    ]
