# Generated by Django 4.1.3 on 2023-04-02 23:07

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('simple_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_event_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='event_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('holidays', 'تعطیلات'), ('meeting', 'جلسه')], max_length=64),
        ),
        migrations.CreateModel(
            name='SimpleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='board.board')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simple_calendar.simplecalendar'),
            preserve_default=False,
        ),
    ]
