# Generated by Django 4.1.3 on 2023-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calendar', '0002_event_custom_event_type_event_event_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('task', 'فعالیت'), ('holidays', 'تعطیلات'), ('meeting', 'جلسه')], max_length=64),
        ),
    ]
