# Generated by Django 4.1.3 on 2023-04-17 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_starred_boards'),
        ('simple_calendar', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('from_date', models.DateField()),
                ('until_date', models.DateField()),
                ('repeat', models.PositiveIntegerField(default=0)),
                ('link', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('NOTSTARTED', 'Not Started'), ('HOLDONG', 'Holding'), ('FINISHED', 'Finished')], default='NOTSTARTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to='accounts.profile')),
            ],
        ),
    ]
