# Generated by Django 4.1.3 on 2023-04-17 16:41

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calendar', '0004_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='simple_calendar.simplecalendar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
