# Generated by Django 4.1.3 on 2023-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calendar', '0006_alter_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.TimeField(),
        ),
    ]
