# Generated by Django 4.1.3 on 2023-04-19 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calendar', '0008_meeting_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=110, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
