# Generated by Django 4.1.3 on 2023-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calendar', '0009_alter_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='operator_pass',
            field=models.CharField(default='classicguys', max_length=48),
            preserve_default=False,
        ),
    ]
