# Generated by Django 4.1.3 on 2023-04-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calendar', '0010_meeting_operator_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='operator_pass',
        ),
    ]
