# Generated by Django 4.1.3 on 2023-04-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_calendar', '0011_remove_meeting_operator_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
